export function toggleContent() {
    // Select all toggle buttons
    const buttons = document.querySelectorAll('.toggle-button');

    buttons.forEach(button => {
        button.addEventListener('click', () => {
            //find the nearest hidden-content relative to the button
            const content = button.parentElement.previousElementSibling;

            if (!content) {
                console.error('error: No hidden content found');
                return;
            }

            if (content.style.display === 'none' || content.style.display === '') {
                content.style.display = 'block';
                button.innerHTML = 'View Less <span class="arrow">▲</span>';
            } else {
                content.style.display = 'none';
                button.innerHTML = 'View More <span class="arrow">▼</span>';
            }
        });
    });
}

// AI Summarization function
export function summarizeWithAI() {
    console.log('AI summarize function called!'); // Debug log
    const button = document.querySelector('.ai-summarize-button');
    const originalText = button.textContent;
    
    // Get the journey text
    const journeyText = `From an early age, I always thought coding was the coolest thing. I remember spending time on various websites, using the "Inspect Element" tool to peek behind the scenes, wondering how everything worked. I would play around with editing or deleting code, amazed at how simple changes could affect the way a website looked or functioned. As a kid, I watched countless YouTube videos, trying to learn more about what went on behind the scenes in coding and technology. This hands-on tinkering and curiosity fueled my passion for tech. In high school, I took coding classes, and it became clear to me that coding was more than just a hobby, it was the profession I wanted to pursue. My brother, who is also a Computer Science graduate with a master's degree, has been a big inspiration and a mentor to me. He has guided me not only in the field but also in learning new tools and technologies, motivating me to continue my path in tech. This passion brought me to Auburn University, where I am working on my degree in Computer Science and a minor in Statistics with a focus on data science. My academic journey has allowed me to explore fields like software development and machine learning. My love for coding and technology has only grown stronger as I've built projects and tackled challenges that combine problem-solving with data-driven insights. Throughout my journey, I've gained experience with multiple programming languages, tools, and technologies, applying them to both personal projects and academic work. I'm always eager to learn more and advance my skills, and in the future, I hope to pursue a master's degree to deepen my knowledge and expertise. With each new project, my desire to contribute to real-world technological advancements grows, and my goal is to use my skills to make meaningful contributions in the tech industry.`;

    // Show loading state
    button.textContent = 'Summarizing...';
    button.disabled = true;

    // Real AI using Netlify Function (secure for public use)
    fetch('/.netlify/functions/summarize', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            text: journeyText
        })
    })
    .then(response => response.json())
    .then(data => {
        if (data && data.summary) {
            showSummary(data.summary);
        } else {
            showSummary("AI summarization is currently unavailable. Please read the full journey above!");
        }
    })
    .catch(error => {
        console.error('Error:', error);
        showSummary("AI summarization is currently unavailable. Please read the full journey above!");
    })
    .finally(() => {
        button.textContent = originalText;
        button.disabled = false;
    });
}

function showSummary(summary) {
    // Create or update summary display
    let summaryDiv = document.getElementById('ai-summary');
    if (!summaryDiv) {
        summaryDiv = document.createElement('div');
        summaryDiv.id = 'ai-summary';
        summaryDiv.className = 'ai-summary';
        summaryDiv.style.cssText = `
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 10px;
            margin: 20px 0;
            box-shadow: 0 4px 15px rgba(0,0,0,0.1);
            font-style: italic;
        `;
        
        // Insert after the journey section
        const journeySection = document.querySelector('#about');
        journeySection.appendChild(summaryDiv);
    }
    
    summaryDiv.innerHTML = `
        <h4>AI Summary:</h4>
        <p>"${summary}"</p>
        <small>Generated by AI • <button onclick="this.parentElement.parentElement.remove()" style="background: none; border: none; color: white; text-decoration: underline; cursor: pointer;">Dismiss</button></small>
    `;
}

document.addEventListener('DOMContentLoaded', () => {
    toggleContent();
    
    // Make the AI function globally available
    window.summarizeWithAI = summarizeWithAI;
});
